[package]
name = "microsoft-dia"
version = "0.3.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rust for Debug Interface Access (DIA) SDK"
repository = "https://github.com/microsoft/dia-rs"
documentation = ""
readme = "README.md"
exclude = [".github", ".windows", ".metadata", "docs", "tests"]

[workspace]
members = [
    "crates/tools/*",
    "crates/samples/*",
]

[dependencies.windows]
version = "0.34"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole"
]

[features]
implement = []