[package]
name = "microsoft-dia"
version = "0.11.0"
authors = ["Microsoft"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rust for Debug Interface Access (DIA) SDK"
repository = "https://github.com/microsoft/dia-rs"
readme = ".github/README.md"
exclude = [".github", ".metadata", "docs", "tests"]

[workspace]
members = ["crates/samples/*"]

[dependencies.windows]
branch = "bindgen-vnext"
git = "https://github.com/microsoft/windows-rs"
features = [
    "Win32_System_Variant",
    "Win32_System_LibraryLoader",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
]

[dependencies.windows-core]
branch = "bindgen-vnext"
git = "https://github.com/microsoft/windows-rs"

[build-dependencies.windows-bindgen]
branch = "bindgen-vnext"
git = "https://github.com/microsoft/windows-rs"
