[package]
name = "microsoft-dia"
version = "0.16.0"
authors = ["Microsoft"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Rust for Debug Interface Access (DIA) SDK"
repository = "https://github.com/microsoft/dia-rs"
readme = ".github/README.md"
exclude = [".github", "docs", "tests"]

[workspace]
members = ["crates/samples/*", "crates/tools/*"]
resolver = "3"

[workspace.dependencies]
windows-core = "0.100"

[dependencies.windows-core]
workspace = true
