[package]
name = "sample_functions"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.windows]
version = "0.33"
features = [
    "alloc",
    "Win32_System_Com"
]

[dependencies.microsoft-dia]
path = "../../../"
