[package]
name = "sample_functions"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.windows]
version = "0.36"
features = [
    "alloc"
]

[dependencies.microsoft-dia]
path = "../../../"
