name: CI

on:
  pull_request:
  push:
    branches:
      - master
env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          rust: stable
          other: x86_64-pc-windows-msvc
          platform: x64
        - os: windows-latest
          rust: nightly
          other: i686-pc-windows-msvc
          platform: x86
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update toolchain
      run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}

    - name: Add toolchain target
      run: rustup target add ${{ matrix.other }}

    - name: Build (${{ matrix.os }})
      run: cargo test --all --target ${{ matrix.other }}

  cargo_fmt:
    name: Check cargo formatting
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cargo fmt
      run: cargo fmt --all -- --check

  cargo_clippy:
    name: Check cargo clippy
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cargo clippy
      run: cargo clippy --all -- -D warnings

  cargo_doc:
    name: Check cargo docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run cargo doc
      run: cargo doc --no-deps
